### ISSUE TITLE
Plugin description can be misleading

### ISSUE THREAD

**Issue by notshwuy** [zhaoworks/feh#4]
> feh stands for Fastify Error Handler, it's a plugin to facilitate and standardize error management in your Fastify application.

Real unrecoverable errors are not handled by this library; it is more likely that this library is an error response normalizer than a handler.

The library name and it's reason still great, but it is the name and it's meaning in "stands" that can be misleading. 😅

**Comment by kauefraga** [comment]
Sure, maybe "It's a plugin to facilitate and standardize error responses in your Fastify application." suits better. What you think?

**Comment by notshwuy** [comment]
> feh is a Fastify Error Responder, it's a plugin to facilitate and standardize error management in your Fastify application.

Maybe replacing meaning with what the plugin actually is could help more, not a big deal but just changing to this should look more ok-ish.
